apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: thanos-sidecar
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 3.5.0
    monitoring.openshift.io/collection-profile: telemetry
  name: thanos-sidecar-telemetry
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: ""
    interval: 30s
    metricRelabelings:
    - action: keep
      regex: (ALERTS|prometheus_tsdb_head_series|up|scrape_samples_post_metric_relabeling|scrape_series_added)
      sourceLabels:
      - __name__
    port: thanos-proxy
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
      insecureSkipVerify: false
      keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
      serverName: thanos-sideca.openshift-monitoring.svc
  scrapeClass: tls-client-certificate-auth
  selector:
    matchLabels:
      app.kubernetes.io/component: thanos-sidecar
