apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: monitoring-plugin
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: monitoring-plugin
    app.kubernetes.io/part-of: openshift-monitoring
  name: monitoring-plugin
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: ""
    honorLabels: true
    interval: 30s
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: false
      serverName: monitoring-plugin.openshift-monitoring.svc
  scrapeClass: tls-client-certificate-auth
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring-plugin
      app.kubernetes.io/name: monitoring-plugin
      app.kubernetes.io/part-of: openshift-monitoring
