{
 "title": "API Performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "apiserver",
    "label": "apiserver",
    "query": "label_values(apiserver_request_duration_seconds_bucket, apiserver)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(apiserver_request_total, instance)"
   },
   {
    "name": "resource",
    "label": "resource",
    "query": "label_values(apiserver_request_duration_seconds_bucket, resource)"
   },
   { "name": "code", "label": "code", "query": "label_values(code)" },
   { "name": "verb", "label": "verb", "query": "label_values(verb)" },
   { "name": "flowSchema", "label": "flow-schema", "query": "label_values(flowSchema)" },
   { "name": "priorityLevel", "label": "priority-level", "query": "label_values(priorityLevel)" },
   { "name": "period", "label": "interval", "query": "1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "request duration - 99th quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[$period])) by(verb,le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "rpc by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\",verb=~\"$verb\"}[$period])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "request status rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\",code=~\"$code\",code=~\"2..\"}[$period]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\",code=~\"$code\",code=~\"3..\"}[$period]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\",code=~\"$code\",code=~\"4..\"}[$period]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\",code=~\"$code\",code=~\"5..\"}[$period]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "rpc by resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\"}[$period])) by(resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "request in flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{apiserver=\"$apiserver\",instance=~\"$instance\"}) by (instance,requestKind)",
     "legendFormat": "{{requestKind}}-{{instance}}"
    }
   ]
  },
  {
   "title": "long running requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "requests dropped rate",
   "type": "graph",
   "description": "Number of requests dropped with 'Try again later' response",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_dropped_requests_total{apiserver=\"$apiserver\",instance=~\"$instance\"}[$period])) by (requestKind)"
    }
   ]
  },
  {
   "title": "requests terminated rate",
   "type": "graph",
   "description": "Number of requests which apiserver terminated in self-defense.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\"}[$period])) by(component)"
    }
   ]
  },
  {
   "title": "response size - 99th quantile",
   "type": "graph",
   "description": "Response size distribution in bytes for each group, version, verb, resource, subresource, scope and component.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_response_sizes_bucket{apiserver=\"$apiserver\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\"}[$period])) by(instance,le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "p&f - requests rejected ",
   "type": "graph",
   "description": "Number of requests rejected by API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_flowcontrol_rejected_requests_total{apiserver=\"$apiserver\",instance=~\"$instance\",flowSchema=~\"$flowSchema\",priorityLevel=~\"$priorityLevel\"}[$period])) by (reason)"
    }
   ]
  },
  {
   "title": "p&f - request wait duration - 99th quantile",
   "type": "graph",
   "description": "Length of time a request spent waiting in its queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_wait_duration_seconds_bucket{apiserver=\"$apiserver\",instance=~\"$instance\",flowSchema=~\"$flowSchema\",priorityLevel=~\"$priorityLevel\"}[$period])) by(flowSchema, priorityLevel, le))",
     "legendFormat": "{{flowSchema}}:{{priorityLevel}}"
    }
   ]
  },
  {
   "title": "p&f - request queue length ",
   "type": "graph",
   "description": "Length of queue in the API Priority and Fairness system, as seen by each request after it is enqueued",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_queue_length_after_enqueue_bucket{apiserver=\"$apiserver\",instance=~\"$instance\",flowSchema=~\"$flowSchema\",priorityLevel=~\"$priorityLevel\"}[$period])) by(flowSchema, priorityLevel, le))",
     "legendFormat": "{{flowSchema}}:{{priorityLevel}}"
    }
   ]
  },
  {
   "title": "p&f - request dispatch rate ",
   "type": "graph",
   "description": "Number of requests released by API Priority and Fairness system for service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_flowcontrol_dispatched_requests_total{apiserver=\"$apiserver\",instance=~\"$instance\",flowSchema=~\"$flowSchema\",priorityLevel=~\"$priorityLevel\"}[$period])) by(flowSchema,priorityLevel)",
     "legendFormat": "{{flowSchema}}:{{priorityLevel}}"
    }
   ]
  },
  {
   "title": "p&f - request execution duration ",
   "type": "graph",
   "description": "Duration of request execution in the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_execution_seconds_bucket{apiserver=\"$apiserver\",instance=~\"$instance\",flowSchema=~\"$flowSchema\",priorityLevel=~\"$priorityLevel\"}[$period])) by(flowSchema, priorityLevel, le) ) ",
     "legendFormat": "{{flowSchema}}:{{priorityLevel}}"
    }
   ]
  },
  {
   "title": "p&f - pending in queue ",
   "type": "graph",
   "description": "Number of requests currently pending in queues of the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_current_inqueue_requests{apiserver=\"$apiserver\",instance=~\"$instance\",flowSchema=~\"$flowSchema\",priorityLevel=~\"$priorityLevel\"}) by (flowSchema,priorityLevel)",
     "legendFormat": "{{flowSchema}}:{{priorityLevel}}"
    }
   ]
  },
  {
   "title": "p&f - concurrency limit by priority level ",
   "type": "graph",
   "description": "Shared concurrency limit in the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_request_concurrency_limit{apiserver=\"$apiserver\",instance=~\"$instance\",priorityLevel=~\"$priorityLevel\"}) by (priorityLevel)",
     "legendFormat": "{{priorityLevel}}"
    }
   ]
  }
 ]
}