apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: metrics-server
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 0.9.0
    prometheus: k8s
    role: alert-rules
  name: metrics-server-rules
  namespace: openshift-monitoring
spec:
  groups:
  - name: metrics-server
    rules:
    - alert: MetricsServerKubeletScrapeFailures
      annotations:
        description: metrics-server in namespace {{ $labels.namespace }} (pod {{ $labels.pod }}) is failing {{ $value | humanizePercentage }} of the requests to kubelet. Check metrics-server logs for "Failed to scrape node".
        summary: metrics-server fails to scrape nodes.
      expr: |
        sum by (pod, namespace) (
          rate(metrics_server_kubelet_request_total{namespace="openshift-monitoring",success="false"}[5m])
        )
        /
        sum by (pod, namespace) (
          rate(metrics_server_kubelet_request_total{namespace="openshift-monitoring"}[5m])
        )
        > 0.1
      for: 15m
      labels:
        namespace: openshift-monitoring
        severity: warning
